language: go

services:
  - docker

matrix:
  fast_finish: true
  include:
  - go: "1.13.x"
    env:
      - PUBLISH="true"
  allow_failures:
  - go: "master"
    env:
      - PUBLISH="false"
env:
  global:
    - VERSION=${TRAVIS_BUILD_NUMBER}
    - BRANCH=${TRAVIS_BRANCH}

before_install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

install:
  - go get ./...

script:
  - make lint
  - make test

after_success:
  - docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
  - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

deploy:
- provider: script
  cleanup: false
  script: GITHUB_TOKEN=${GITHUB_TOKEN} make release
  on:
    tags: true
    condition: $PUBLISH = "true"