version: '3'
services:
  httpmole:
    image: jcchavezs/httpmole:main
    volumes:
        - $PWD/response-file.json:/httpmole/response.json
    command: ["-response-file", "/httpmole/response.json"]
    ports:
        - "10080:10080"
